#!/bin/bash
# steps/08-chroot-prep.sh - Prepare chroot environment

set -euo pipefail

run_step() {
    step_start "08-chroot-prep" "Preparing chroot environment"

    # Copy archstrap scripts to chroot for later use
    local chroot_scripts="${MOUNT_POINT}/root/archstrap"
    run mkdir -p "${chroot_scripts}"

    # Copy necessary scripts
    log_info "Copying scripts to chroot environment"
    run cp -r "${SCRIPT_DIR}/lib" "${chroot_scripts}/"
    run cp -r "${SCRIPT_DIR}/steps/chroot" "${chroot_scripts}/"
    run cp -r "${SCRIPT_DIR}/configs" "${chroot_scripts}/"

    # Copy configuration state
    if [[ -f "${CONFIG_FILE}" ]]; then
        run cp "${CONFIG_FILE}" "${chroot_scripts}/archstrap.conf"
    fi
    if [[ -f "${STATE_FILE}" ]]; then
        run cp "${STATE_FILE}" "${chroot_scripts}/archstrap.state"
    fi

    # Create swapfile
    local swap_size
    swap_size="$(state_get swap_size)"
    if [[ -n "${swap_size}" ]]; then
        log_info "Creating swapfile: ${swap_size}"
        create_swapfile "${MOUNT_POINT}" "${swap_size}"

        # Get swapfile offset for hibernation
        if [[ "${DRY_RUN}" != "1" ]]; then
            local swap_offset
            swap_offset="$(get_swapfile_offset "${MOUNT_POINT}/swap/swapfile")"
            if [[ -n "${swap_offset}" ]]; then
                state_set "swap_offset" "${swap_offset}"
                log_info "Swapfile offset: ${swap_offset}"
            fi
        fi
    fi

    # Copy resolv.conf for network access in chroot
    if [[ "${DRY_RUN}" != "1" ]]; then
        cp /etc/resolv.conf "${MOUNT_POINT}/etc/resolv.conf"
    fi

    # Configure mkinitcpio early so it's in place before any rebuilds
    # (e.g., hardware quirks that might trigger mkinitcpio)
    log_info "Configuring mkinitcpio"
    if [[ "${DRY_RUN}" != "1" ]]; then
        # Build MODULES array based on detected hardware
        local mkinitcpio_modules="btrfs"

        # Add GPU modules for early KMS (required for Plymouth)
        local gpus
        gpus="$(detect_gpu)"

        if [[ "${gpus}" == *"nvidia"* ]]; then
            mkinitcpio_modules="${mkinitcpio_modules} nvidia nvidia_modeset nvidia_uvm nvidia_drm"
        fi
        if [[ "${gpus}" == *"intel"* ]]; then
            mkinitcpio_modules="${mkinitcpio_modules} i915"
        fi
        if [[ "${gpus}" == *"amd"* ]]; then
            mkinitcpio_modules="${mkinitcpio_modules} amdgpu"
        fi

        # Build HOOKS array
        local mkinitcpio_hooks="systemd autodetect microcode modconf kms keyboard sd-vconsole plymouth sd-encrypt block filesystems fsck"

        # Add AppArmor hook if enabled AND the hook exists (must come before sd-encrypt)
        if [[ "$(config_get enable_apparmor)" == "1" ]]; then
            if [[ -f "${MOUNT_POINT}/usr/lib/initcpio/install/apparmor" ]]; then
                mkinitcpio_hooks="systemd autodetect microcode modconf kms keyboard sd-vconsole plymouth apparmor sd-encrypt block filesystems fsck"
                log_info "AppArmor mkinitcpio hook found and enabled"
            else
                log_warn "AppArmor enabled but mkinitcpio hook not found"
                log_warn "AppArmor will be enabled at runtime but not in initramfs"
            fi
        fi

        cat > "${MOUNT_POINT}/etc/mkinitcpio.conf" << EOF
# Generated by archstrap
MODULES=(${mkinitcpio_modules})
BINARIES=()
FILES=()
HOOKS=(${mkinitcpio_hooks})
EOF
        log_info "mkinitcpio.conf configured with hooks: ${mkinitcpio_hooks}"
    fi

    state_save
    log_info "Chroot preparation complete"
}
